# Generated by Django 5.2.3 on 2025-07-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="users.therapistprofile",
            ),
        ),
        migrations.AddField(
            model_name="therapistprofile",
            name="therapist_pin",
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
