# Generated by Django 5.2.3 on 2025-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_patientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='history_id',
            field=models.UUIDField(blank=True, help_text='ID linking to patient history records', null=True),
        ),
    ]
