# Generated by Django 5.2.3 on 2025-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_patientprofile_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Patient's address", null=True),
        ),
    ]
