# Generated by Django 5.2.3 on 2025-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_address_to_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_linked_account',
            field=models.BooleanField(default=False, help_text='True if this patient profile is linked to a user account'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='linked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the account was linked', null=True),
        ),
    ]
