# Generated by Django 5.2.3 on 2025-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_account_linking_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['patient_id'], name='patient_id_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['therapist', 'connected_at'], name='therapist_connected_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['is_linked_account'], name='linked_account_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['created_by_therapist'], name='created_by_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientprofile',
            constraint=models.CheckConstraint(condition=models.Q(('session_frequency__in', ['weekly', 'biweekly', 'monthly', 'as_needed'])), name='valid_session_frequency'),
        ),
    ]
