# Generated by Django 5.2.3 on 2025-07-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_session_ai_key_topics_session_ai_mood_analysis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientPairingRequest',
        ),
    ]
