# Generated by Django 5.2.3 on 2025-07-31 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0003_remove_patient_pairing_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['therapist', 'scheduled_date'], name='therapist_date_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['patient', 'scheduled_date'], name='patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status', 'scheduled_date'], name='status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_quick_session'], name='quick_session_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['transcription_id'], name='transcription_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 15)), name='min_duration'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__lte', 480)), name='max_duration'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient_mood_before__gte', 1), ('patient_mood_before__lte', 10)), ('patient_mood_before__isnull', True), _connector='OR'), name='valid_mood_before'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('patient_mood_after__gte', 1), ('patient_mood_after__lte', 10)), ('patient_mood_after__isnull', True), _connector='OR'), name='valid_mood_after'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_effectiveness__gte', 1), ('session_effectiveness__lte', 10)), ('session_effectiveness__isnull', True), _connector='OR'), name='valid_effectiveness'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_quick_session', True), ('quick_session_patient_name__isnull', False)), models.Q(('is_quick_session', False), ('patient__isnull', False)), _connector='OR'), name='patient_or_quick_name'),
        ),
    ]
