# Generated by Django 5.2.3 on 2025-07-31 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0004_session_therapist_date_idx_session_patient_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='websocket_active',
            field=models.BooleanField(default=False, help_text='Whether WebSocket connection is active'),
        ),
        migrations.AddField(
            model_name='session',
            name='websocket_room_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique room ID for WebSocket connection', unique=True),
        ),
    ]
