# Generated by Django 5.2.3 on 2025-07-08 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0002_alter_emailverificationtoken_expires_at_refreshtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 16, 13, 13, 445939, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
