# Generated by Django 5.2.3 on 2025-07-08 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0003_alter_emailverificationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 9, 16, 21, 1, 669381, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
