# Generated by Django 5.2.3 on 2025-07-09 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0004_alter_emailverificationtoken_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 10, 8, 19, 42, 572584, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
