# Generated by Django 5.2.3 on 2025-07-09 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticator", "0005_alter_emailverificationtoken_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 10, 8, 21, 48, 707153, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
