# Generated by Django 5.2.3 on 2025-07-13 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0007_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 7, 8, 0, 672050, tzinfo=datetime.timezone.utc)),
        ),
    ]
