# Generated by Django 5.2.3 on 2025-07-31 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0012_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 6, 34, 55, 83014, tzinfo=datetime.timezone.utc)),
        ),
    ]
