# Generated by Django 5.2.3 on 2025-07-31 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0013_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 8, 57, 32, 521692, tzinfo=datetime.timezone.utc)),
        ),
    ]
