# Generated by Django 5.2.3 on 2025-08-01 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0017_alter_emailverificationtoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 19, 33, 24, 4796, tzinfo=datetime.timezone.utc)),
        ),
    ]
